### ISSUE TITLE
Profiles: Laborverordnung ohne Verwendung von Questionnaire / QuestionnaireResponse fehlt (Emmanuel Eschmann, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-order#81]
ch.fhir.ig.ch-lab-order#0.1.0 /profiles.html

Der täglich 100’000-fach genutzte Anwendungsfall von Inhouse – Laborverordnungen (z.Bsp. von einem KIS zu einem LIS im selben Spital) fehlt. Dieser Anwendungsfall nutzt typischerweise eine im KIS integrierte und für die Erfassung durch klinische Benutzer optimierte Laborverordnung (inkl. hinterlegter Analysepanels).

Solche u.a. durch Erfassungsassistenten, Clinical Decision Support-Systeme oder Patienten-Workflows gesteuerte voll-integrierte Laborverordnungssysteme können kaum ohne Einbussen oder unnötigem Aufwand mit den in «CH LAB-Order Composition» verlangten Questionnaire und QuestionnaireResponse abgebildet werden. Dagegen wäre ihre direkte Abbildung in ServiceRequests (ohne Questionnaire / QuestionnaireResponse) zielführender. Da oft mehrere Laboruntersuchungen für dieselbe Entnahmeprobe verordnet werden, sollen mehrere ServiceRequests mithilfe des «Request Pattern» verbunden werden können (siehe http://hl7.org/fhir/2020May/request.html#requisitionid).

Diese Problematik der Abbildung voll-integrierter Laborverordnungssysteme mit der Ressource QuestionnaireResponse wird in dem dem «CH LAB-Order» IG zugrundeliegenden Dokument «Swiss eHealth Exchange Format Handbook. Part I: Service Requests. V0.13, Final Draft» (https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/E/Exchange-format-handbook_part-1_v12.pdf) auf S. 21 beschrieben: «Another consideration refers to use cases where an application populates almost all items of a structured document. In such cases, population of the concerned re-sources may be more attractive than a detour via a questionnaire. […] In such a case, there would be no QuestionnaireResponse Resource in the bundle because all content is already in concerning resources.” Im Widerspruch dazu folgt im selben Dokument der Text “Having said this, the authors of this handbook conclude: Exchange formats which use the ServiceRequest Resource SHALL define a questionnaire […].”

Damit sich der vorliegende IG durchsetzen kann, muss er den o.g. mengenmässig sehr häufige Anwendungsfall von Inhouse-Verordnungen abbilden können (in den «Case Studies», «Use Cases», «Profiles» und Beispielinstanzen; ohne Verwendung von Questionnaire / QuestionnaireResponse).

Vorschlag:
- 1: Entweder IG und Profile umbenennen auf «Laborverordnungen auf Basis Forms/Questionnaires» und neues IG für «Laborverordnungen ohne Forms/Questionnaires» erstellen
- oder 2: dieses IG um «Laborverordnungen ohne Forms/Questionnaires» ergänzen

Emmanuel Eschmann, CISTEC AG

**Comment by siwal** [comment]
Ich unterstütze dies ebenfalls. Dieser Anwendungsfall fehlt komplett. Die Variante mit Questionnaire und QuestionnaireResponse wird primär bei der Kommunikation zwischen Institutionen zum Einsatz kommen.
Beispiele:
- Spital A <-> Spital B
- Praxis A <-> Labor A
- Labor A <-> Labor B
- Spital A <-> ext. Labor A

Simon Walther, CISTEC AG

**Comment by lpg-tech** [comment]
Zu diskutieren: Vorschlag 2 von Emmanuel und den UC um «Laborverordnungen ohne Forms/Questionnaires» ergänzen

**Comment by JBleuer** [comment]
Emanuel schreibt: "Im Widerspruch dazu folgt im selben Dokument der Text “Having said this, the authors of this handbook conclude: Exchange formats which use the ServiceRequest Resource SHALL define a questionnaire […].”

Das sit kein Widerspruch: Etwas oberhalb steht im Exchange Format Handbook: "For further discussion, it may be helpful to be aware that defining a questionnaire and its implementation are two separate things. In other words: authors of a particular implementation guide may decide to define a questionnaire and its rendering but to leave it open if in a particular implementation the questionnaire is implemented or if the representation towards the user is made
(in accordance to the questionnaire definition) by other technical means. In such a case, there
would be no QuestionnaireResponse Resource in the bundle because all content is already in
concerning resources."

Gemeint ist: Autoren von weiteren (ORF-basierten) IS sollen einen Questionnaire /QR definieren; dies als Leitlinie, wie ein User Interface aussehen soll. Implementers eines solchen IG können das UI aber auch mit anderen Mitteln realisieren.
Die Cardinality im Bundle muss deshalb für Q und QR 0..1 sein; das wurde mittlerweile berichtigt.

**Comment by PeroGrgic** [comment]
Issue reviewed and closed.
